settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 7 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统正常运行'
  notAllmonitorsOperational: '部分运行异常'
  monitorLabelOperational: '正常'
  monitorLabelNotOperational: '异常'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: lobe
    name: lobe
    description: ''
    url: 'https://lobe.qinks6.eu.org'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
    
  - id: clash
    name: clash
    description: ''
    url: 'https://clash.qinks6.eu.org'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: bitwarden
    name: bitwarden
    description: ''
    url: 'https://bitwarden.qinks6.eu.org/admin'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

